---
name: Quality Assurance
on:
  push:
    paths:
      - src/**/*.php
      - .github/workflows/quality-assurance.yml
    branches:
      - 2.x
  pull_request:
    paths:
      - src/**/*.php
      - .github/workflows/quality-assurance.yml
    branches:
      - 2.x

jobs:
  phpunit:
    name: PHPUnit tests on ${{ matrix.php }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
        composer-flags: [ '' ]
        experimental: [false]
        phpunit-flags: [ '--coverage-text' ]
        include:
          - php: '7.4'
            composer-flags: '--prefer-lowest'
            experimental: false
            phpunit-flags: '--no-coverage'
          - php: '8.2'
            composer-flags: '--ignore-platform-reqs'
            experimental: true
            phpunit-flags: '--no-coverage'
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - run: composer update --no-progress ${{ matrix.composer-flags }}
      - run: COMPOSER_OPTS='${{ matrix.composer-flags }}' vendor/bin/phpunit ${{ matrix.phpunit-flags }}
      - run: vendor/bin/phpstan analyse
        if: ${{ matrix.php == '7.4' }}
      - run: vendor/bin/php-cs-fixer fix --diff --dry-run
        continue-on-error: true
        if: ${{ matrix.php == '7.4' }}
