---
name: Quality Assurance

on:
    pull_request: ~
    push: ~
    schedule:
        - cron: "32 8 23 * *"

jobs:
    quality-assurance:
        runs-on: "ubuntu-latest"
        continue-on-error: "${{ matrix.continue-on-error }}"
        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1", "8.2", "8.3", "8.4", "8.5"]
                dependency-versions: ["highest"]
                composer-stable: ["1"]
                continue-on-error: [false]
                include:
                    - php: "8.0"
                      dependency-versions: "lowest"
                      composer-stable: "1"
                      continue-on-error: false
                    - php: "latest"
                      composer-flags: ''
                      continue-on-error: true

        name: "PHP ${{ matrix.php }} - Composer ${{ matrix.dependency-versions }}"

        steps:
            - name: "checkout"
              uses: "actions/checkout@v4"

            - name: "setup php"
              uses: "shivammathur/setup-php@v2"
              with:
                php-version: "${{ matrix.php }}"
                tools: "composer"

            - name: "install composer dependencies"
              uses: "ramsey/composer-install@v3"
              env:
                COMPOSER_PREFER_STABLE: "${{ matrix.composer-stable }}"
              with:
                dependency-versions: "${{ matrix.dependency-versions }}"

            - name: "run phpunit tests"
              run: "vendor/bin/phpunit --colors=always"

            - name: "run phpstan static analysis"
              run: "vendor/bin/phpstan analyse --ansi"
              if: ${{ matrix.php == '8.4' }}

            - name: "run coding standards check"
              run: "vendor/bin/php-cs-fixer fix --diff --dry-run"
              if: ${{ matrix.php == '8.4' }}
